site_name: AD - AccÃ©s a Dades - Ficheros

extra_css:
  - css/extra.css
  - img/favicon.ico 

theme: 
  name: readthedocs
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - copy-to-clipboard
    - content.code.copy
  #highlightjs: true
  logo: assets/logocaminas.png
    

#extra_javascript:
#  - js/extra.js


markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc
  - md_in_html

nav:
  - ğŸ”¹IntroducciÃ³n: intro.md
  - ğŸ”¹IntelliJ IDEA Ultimate : Idea.md
  - ğŸ”¹Entrega Ejercicios: ejercicios.md
  - ğŸ”¹Kotlin: Kotlin.md  
  #- ğŸ”¹Docker: docker.md
